name: CI/CD for .NET Solution (Local Docker)

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-and-deploy:
    runs-on: self-hosted

    env:
      IMAGE_NAME: ${{ github.ref_name == 'develop' && secrets.DEV_DOCKER_IMAGE_NAME || secrets.DOCKER_IMAGE_NAME }}
      DOCKER_PORT: ${{ github.ref_name == 'develop' && secrets.DEV_DOCKER_PORT || secrets.DOCKER_PORT }}
      APP_PORT: ${{ github.ref_name == 'develop' && secrets.DEV_APP_PORT || secrets.APP_PORT }}
      CONNECTIONSTRING: ${{ github.ref_name == 'develop' && secrets.DEV_CONNECTIONSTRING || secrets.CONNECTIONSTRING }}
      ASPNETCORE_ENVIRONMENT: ${{ github.ref_name == 'develop' && 'Development' || 'Production' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up environment for .NET installation
        run: |
          echo "DOTNET_ROOT=$HOME/.dotnet" >> $GITHUB_ENV
          echo "$HOME/.dotnet:$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Build Docker Image
        run: |
          docker build -t $IMAGE_NAME:v1 .

      - name: Stop and Remove Old Container (if exists)
        run: |
          docker stop $IMAGE_NAME || true
          docker rm $IMAGE_NAME || true

      - name: Run Docker Container
        run: |
          docker run -d --name $IMAGE_NAME \
            --network mascoteach-network \
            --restart unless-stopped \
            -e ConnectionStrings__DefaultConnection="$CONNECTIONSTRING" \
            -e ASPNETCORE_ENVIRONMENT="$ASPNETCORE_ENVIRONMENT" \
            -e AWS__AccessKey="${{ secrets.AWS_ACCESS_KEY }}" \
            -e AWS__SecretKey="${{ secrets.AWS_SECRETKEY }}" \
            -e AWS__Region="${{ secrets.AWS_REGION }}" \
            -e AWS__BucketName="${{ secrets.AWS_BUCKETNAME }}" \
            -e AWS__PRESIGNEDURLEXPIRATIONMINUTES="${{ secrets.AWS_PRESIGNEDURLEXPIRATIONMINUTES }}" \
            -p $DOCKER_PORT:$APP_PORT $IMAGE_NAME:v1